### ISSUE TITLE
Logo Design For Notes

### ISSUE THREAD

**Issue by zularizal** [K0bin/Notes#1]
Hi @K0bin ,I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by zularizal** [comment]
I'm making 3 logos for you, which one do you like?
I can provide foreground and background after you select the logo you like. If there is something you want to change please let me know.

![logo](https://user-images.githubusercontent.com/38547278/42059847-007a8a82-7b4f-11e8-9373-d782d1664200.png)

**Comment by zularizal** [comment]
Okay, wait a minute, I'll upload the logo to the drive and send a pull request.

**Comment by zularizal** [comment]
Hi, I already uploaded the logo to drive, this is the link

https://drive.google.com/open?id=1Tk2CtQdr_kjWcvwKoLRdGYZ3Liu7v6GG

and also I have sent a pull request for you, please check #7 

And I'm sorry yesterday I was too busy so I forget this

**Comment by zularizal** [comment]
Okay, i will close this issue

**Comment by K0bin** [comment]
The logo of course looks great but the files you provided are quite low resolution.

Can you provide these as at least 512x512 without any margin?

**Comment by zularizal** [comment]
Okay, it's added to drive

https://drive.google.com/open?id=1JKdfhaYnqIDKMoGY5XyQ4d7ays55pzLN

**Comment by K0bin** [comment]
Thank you!

**Comment by zularizal** [comment]
It's my pleasure :+1:
